// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEWbuDPlwsK7dfjE_-t90MgGbwvQjPStE',
    appId: '1:935284675226:web:56383648c653188d024523',
    messagingSenderId: '935284675226',
    projectId: 'growio-b5294',
    authDomain: 'growio-b5294.firebaseapp.com',
    storageBucket: 'growio-b5294.firebasestorage.app',
    measurementId: 'G-VYQJSEGDDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuTAEbSw8HV73rVAKNK1ifU1mL5mXxFbk',
    appId: '1:935284675226:android:b09bea11cbeea015024523',
    messagingSenderId: '935284675226',
    projectId: 'growio-b5294',
    storageBucket: 'growio-b5294.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEWbuDPlwsK7dfjE_-t90MgGbwvQjPStE',
    appId: '1:935284675226:web:307c710ccb192c55024523',
    messagingSenderId: '935284675226',
    projectId: 'growio-b5294',
    authDomain: 'growio-b5294.firebaseapp.com',
    storageBucket: 'growio-b5294.firebasestorage.app',
    measurementId: 'G-DJ046M1RDH',
  );
}
